import 'package:flutter/material.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = [Locale('ru'), Locale('en')];

  static const Map<String, Map<String, String>> _values = {
    'ru': {
      'appName': 'Ritmio',
      'dashboard': 'Дашборд',
      'transactions': 'Транзакции',
      'tasks': 'Задачи',
      'categories': 'Категории',
      'login': 'Вход',
      'register': 'Регистрация',
      'name': 'Имя',
      'email': 'Email',
      'password': 'Пароль',
      'loading': 'Загрузка...',
      'createAccount': 'Создать аккаунт',
      'signIn': 'Войти',
      'alreadyHaveAccount': 'Уже есть аккаунт? Войти',
      'noAccount': 'Нет аккаунта? Зарегистрироваться',
      'authSubtitle': 'Контролируйте финансы и задачи в одном месте',
      'invalidName': 'Введите имя',
      'invalidEmail': 'Введите корректный email',
      'invalidPassword': 'Минимум 8 символов',
      'yourBalance': 'Ваш баланс',
      'weekly': 'Неделя',
      'monthly': 'Месяц',
      'summary': 'Сводка',
      'income': 'Доход',
      'expense': 'Расход',
      'balance': 'Баланс',
      'edit': 'Изменить',
      'delete': 'Удалить',
      'confirm': 'Подтвердить',
      'complete': 'Завершить',
      'cancelTask': 'Отменить задачу',
      'createTransaction': 'Создать транзакцию',
      'editTransaction': 'Изменить транзакцию',
      'createTask': 'Создать задачу',
      'editTask': 'Изменить задачу',
      'createCategory': 'Создать категорию',
      'editCategory': 'Изменить категорию',
      'cancel': 'Отмена',
      'save': 'Сохранить',
      'amount': 'Сумма',
      'date': 'Дата YYYY-MM-DD',
      'category': 'Категория',
      'merchant': 'Магазин',
      'description': 'Описание',
      'title': 'Название',
      'priority': 'Приоритет',
      'dueDate': 'Срок YYYY-MM-DD',
      'slug': 'Slug',
      'nameRu': 'Название RU',
      'nameEn': 'Название EN',
      'incomeType': 'Доход',
      'expenseType': 'Расход',
      'low': 'Низкий',
      'normal': 'Средний',
      'high': 'Высокий',
      'language': 'Язык',
      'russian': 'Русский',
      'english': 'English',
      'settings': 'Настройки',
      'currency': 'Валюта',
      'settingsSaved': 'Настройки сохранены',
      'details': 'Детали',
      'deleteConfirm': 'Удалить?',
      'deleteConfirmMsg': 'Это действие нельзя отменить.',
      'status': 'Статус',
      'source': 'Источник',
      'type': 'Тип',
      'needsConfirmation': 'Требует подтверждения',
      'swipeLeftHint': 'детали',
      'swipeRightHint': 'удалить',
      'logout': 'Выйти из аккаунта',
      'logoutConfirm': 'Вы уверены, что хотите выйти?',
      'yes': 'Да',
      'no': 'Нет',
      'day': 'День',
      'week': 'Неделя',
      'month': 'Месяц',
      'all': 'Все',
      'overview': 'Обзор',
      'calendar': 'Календарь',
      'byDays': 'По дням',
    },
    'en': {
      'appName': 'Ritmio',
      'dashboard': 'Dashboard',
      'transactions': 'Transactions',
      'tasks': 'Tasks',
      'categories': 'Categories',
      'login': 'Login',
      'register': 'Register',
      'name': 'Name',
      'email': 'Email',
      'password': 'Password',
      'loading': 'Loading...',
      'createAccount': 'Create account',
      'signIn': 'Sign in',
      'alreadyHaveAccount': 'Already have an account? Sign in',
      'noAccount': 'No account? Register',
      'authSubtitle': 'Control finance and tasks in one place',
      'invalidName': 'Please enter your name',
      'invalidEmail': 'Please enter a valid email',
      'invalidPassword': 'Minimum 8 characters',
      'yourBalance': 'Your balance',
      'weekly': 'Weekly',
      'monthly': 'Monthly',
      'summary': 'Summary',
      'income': 'Income',
      'expense': 'Expense',
      'balance': 'Balance',
      'edit': 'Edit',
      'delete': 'Delete',
      'confirm': 'Confirm',
      'complete': 'Complete',
      'cancelTask': 'Cancel task',
      'createTransaction': 'Create transaction',
      'editTransaction': 'Edit transaction',
      'createTask': 'Create task',
      'editTask': 'Edit task',
      'createCategory': 'Create category',
      'editCategory': 'Edit category',
      'cancel': 'Cancel',
      'save': 'Save',
      'amount': 'Amount',
      'date': 'Date YYYY-MM-DD',
      'category': 'Category',
      'merchant': 'Merchant',
      'description': 'Description',
      'title': 'Title',
      'priority': 'Priority',
      'dueDate': 'Due date YYYY-MM-DD',
      'slug': 'Slug',
      'nameRu': 'Name RU',
      'nameEn': 'Name EN',
      'incomeType': 'Income',
      'expenseType': 'Expense',
      'low': 'Low',
      'normal': 'Normal',
      'high': 'High',
      'language': 'Language',
      'russian': 'Russian',
      'english': 'English',
      'settings': 'Settings',
      'currency': 'Currency',
      'settingsSaved': 'Settings saved',
      'details': 'Details',
      'deleteConfirm': 'Delete?',
      'deleteConfirmMsg': 'This action cannot be undone.',
      'status': 'Status',
      'source': 'Source',
      'type': 'Type',
      'needsConfirmation': 'Needs confirmation',
      'swipeLeftHint': 'details',
      'swipeRightHint': 'delete',
      'logout': 'Log out',
      'logoutConfirm': 'Are you sure you want to log out?',
      'yes': 'Yes',
      'no': 'No',
      'day': 'Day',
      'week': 'Week',
      'month': 'Month',
      'all': 'All',
      'overview': 'Overview',
      'calendar': 'Calendar',
      'byDays': 'By days',
    },
  };

  String t(String key) {
    final lang = _values[locale.languageCode] ?? _values['en']!;
    return lang[key] ?? key;
  }

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(const Locale('en'));
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      AppLocalizations.supportedLocales.any((l) => l.languageCode == locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async => AppLocalizations(locale);

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) => false;
}
